version: "3.8"
networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.11.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.22.0/24
services:
  mariadb:
    image: "mariadb:${MARIADB_IMAGE_VERSION}"
    restart: always
    env_file: ./etc/docker.env
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./etc/mariadb/init.d:/docker-entrypoint-initdb.d
      - ./etc/mariadb/conf.d:/etc/mysql/conf.d
      - ./var/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend
  kiwi:
    image: "kiwitcms/kiwi:${KIWI_IMAGE_VERSION}"
    restart: always
    env_file: ./etc/docker.env
    depends_on:
      - mariadb
    volumes:
      - ./var/kiwitcms:/Kiwi/uploads
    ports:
      - "8080:8080"
      # - "8443:8443" # for self-gen SSL - not required
    networks:
      - backend
  gitea:
    image: "gitea/gitea:${GITEA_IMAGE_VERSION}"
    restart: always
    env_file: ./etc/docker.env
    depends_on:
      - mariadb
    volumes:
      - ./var/gitea:/data
      - ./etc/tz/sgt_timezone:/etc/timezone:ro
      - ./etc/tz/sgt_localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    networks:
      - backend

    

